### ISSUE TITLE
Did the font color recently change?

### ISSUE THREAD

**Issue by derekvan** [mgmeyers/obsidian-california-coast-theme#122]
I hadn't updated this theme in awhile, but I did yesterday and it appear to me the font color changed to be slightly darker. I checked "style settings" plugin and there doesn't appear to be a way to change the font color. Any chance an option could be added to change it back to the way it was?

**Comment by mgmeyers** [comment]
@derekvan I think what you're describing is caused by this style setting that I added recently: 

<img width="745" alt="Screen Shot 2022-05-03 at 11 46 06 AM" src="https://user-images.githubusercontent.com/2694747/166521734-df8380f4-60b2-4a7c-aecf-b1a269f4cab7.png">

Try setting it to `antialiased` to see if that gets things back to the way you liked them.

**Comment by derekvan** [comment]
I'm not sure. I changed the color to #2A2A2A via CSS and that seems better, but it's so subtle it's possible I'm fooling myself.
