### ISSUE TITLE
Bulleted text cursor is off-center with smaller font

### ISSUE THREAD

**Issue by skalnik** [mgmeyers/obsidian-california-coast-theme#13]
If you pick a smaller font size, it seems the font does get smaller but the line height doesn't match up and the cursor ends up off center. Cursor is aligned right for unbulleted text though!

<img width="647" alt="Screen Shot 2020-12-23 at 11 43 37 🌅" src="https://user-images.githubusercontent.com/2546/103032439-de873f00-4514-11eb-9317-60e028698db0.png">

<img width="720" alt="Screen Shot 2020-12-23 at 11 49 32 🌅" src="https://user-images.githubusercontent.com/2546/103032480-f78ff000-4514-11eb-81e9-f31fccf0472c.png">

**Comment by mgmeyers** [comment]
Thanks @skalnik! This is an unfortunate tradeoff with CodeMirror. The problem is that I've added padding to the bullets, and CodeMirror includes that padding when calculating the caret height. This is also an issue for headings. I originally had a work around for this, but it conflicts with the folding behavior, so I decided to leave it as is. My hope is that this will go away once obsidian implements a proper wysiwyg editor.
