### ISSUE TITLE
Different font for editor and preview

### ISSUE THREAD

**Issue by perfidopelato** [mgmeyers/obsidian-california-coast-theme#51]
I’d be nice to have the option to choose different fonts for editor and preview, like in Minimal theme.

I like for editor and preview to have a very different look, in the editor I like to use Courier because it gives me a more... I don’t know... hands on feeling.

**Comment by mgmeyers** [comment]
Hey @perfidopelato.

With the latest updates this should now be easy enough to do. I didn't want to make these configurable by default, mainly because there are already a lot of settings. But if you pull down the latest theme CSS and install the Style Settings plugin (the California Coast Settings plugin is now deprecated), you can add this to a snippet and you'll be able to configure the preview font separately from the editor:

```css
/* @settings

name: Preview Font
id: preview-font
settings:
    - 
        id: text-preview
        title: Preview Font
        type: variable-text
        default: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif
    -
        id: preview-font-features
        title: Preview font features
        description: eg. "ss01", "cv05", "cv07", "case"
        type: variable-text
        default: ""
    - 
        id: preview-font-size
        title: Preview font size
        description: Font size in px of the main text
        type: variable-number
        default: 18
    - 
        id: preview-line-height
        title: Preview line height
        description: Line height of the main text, expects a decimal value
        type: variable-number
        default: 1.88889  

*/
```

Alternatively, you could override them yourself using these variables:

https://github.com/mgmeyers/obsidian-california-coast-theme/blob/main/src/060-preview.css#L1-L8

In the future, I'll consider adding these along with the other configurable options, but I want to figure out how to better organize the theme settings first.

**Comment by perfidopelato** [comment]
Thanks!! :-)

Inviato da iPad
